server:
  port: 8080

spring:
  profiles:
    active: develop
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    cabanas:
      garcia:
        ismael:
          grandmother: DEBUG
    org:
      hibernate: INFO
