server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        #javax.persistence.schema-generation.create-source: metadata
        #javax.persistence.schema-generation.scripts.action: create
        #javax.persistence.schema-generation.scripts.create-target:  create.sql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${MYPOSTGRES_PORT_5432_TCP_ADDR}:${MYPOSTGRES_PORT_5432_TCP_PORT}/grandmotherdb
    username: postgres
    password: ${MYPOSTGRES_ENV_POSTGRES_PASSWORD}
    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery:  SELECT 1

logging:
  level:
    cabanas:
      garcia:
        ismael:
          grandmother: DEBUG
    org:
      hibernate: INFO

