server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        #javax.persistence.schema-generation.create-source: metadata
        #javax.persistence.schema-generation.scripts.action: create
        #javax.persistence.schema-generation.scripts.create-target:  create.sql
    hibernate:
      ddl-auto: create-drop
    database-platform:  org.hibernate.dialect.MySQL5Dialect
  datasource:
    driverClassName:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.99.100/ManageGrandmotherDb?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: secret
    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery:  SELECT 1

