server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        #javax.persistence.schema-generation.create-source: metadata
        #javax.persistence.schema-generation.scripts.action: create
        #javax.persistence.schema-generation.scripts.create-target:  create.sql
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/grandmotherdb
    username: postgres
    password: secret
    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery:  SELECT 1
logging:
  level:
    cabanas:
      garcia:
        ismael:
          grandmother: DEBUG
    org:
      hibernate: INFO