language: groovy
jdk:
- oraclejdk8
sudo: false
install: true
git:
  depth: 3
script: mvn clean verify
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: euwJsFVwXlb8fB30a3IIQAN/2k3CbTKbUyK/lVEcz3XoCg2AKBbXQlngShThn00ce9/ZSb4004Tyib8Equou9zOqe7UcpqDNBN2hTIT7QGXkE5ZPZ4vhZsJnNORICI3gRthbIfnYxtUIA5oD29SIZQ51Oo8j39B8Ca2RfKCALNsiL7iBFtfBwX7Zm56U53P5ogty6gCoEousMpnSIzTMBi3w7bz59YzwlPjIQhRd1V6rlXKyW4sdgxnOe7IfP5Jj8Zdd0V/jwpA8x+54k58h2DQXPSNZlZuPJR29v3YLC+jYLZimAm30k5oS+pFyYZLD2bTRlt8fJ2ILJNdpJWSK/xX0dWZQFyEpZ6VSovETTslNIwFoFXpIpuucjnTpWYyj8iDF51IWYpISWR+4KuM1lsz/9356Yte3VjRJnx7HvP3pRSp6EBnI6xwr4uMP8VtahWzl+O0fULWq6V8WDVer2PGca2XIRHmGghpBaw7jpJN/QG6K9KqGW0wcCErYZvSc2f00oHyFpijd1LJJcXHqq2caOdMMC9Nwzm9OCrxy9JoOWNbIHtk6RD7Z68B926pHpE8QI7q3LgHyrDkLG6befH+hmonWgrrO9T0KjNg+B1aDBqhhm3+WmjjaKMGeBRPy39gtUyS5aCcXxwPJOwsA9x3QTFpj86999Gyw1PDjBvU=
  on:
    tags: true
