language: groovy
jdk:
  - oraclejdk8
sudo: false
install: true
git:
  depth: 3
addons:
  sonarqube:
    token:
      secure: H60K+a1/R8bgkBZpG6Eb92rS8Iv3e3JcgOtmKeltY7suANtP9oQrOl2o/Q1lECgp2sEF8I49iod4chkgW99MrL2oB+ws9F2MV86az7phDp/XAvYmWlchOEkEvX6swhnGutrH8wpK3a4/FAGbZDBcu0yVDTHLjBLyQTgoOmHk8kFpd2WZvPvjKrprTUmT6VVJlkHKxhFR8h4vObOdZJq7dFcRrRLXwH1wjxEBsmVXU993Emaok6d5d93iyBidb9zfKbXV5XITOBWNkEYHFYbc54bv9YltdkjIjOV8LHeH7wfqlMzwn2GuaXialVLIPnNELUtRP1Pe8XNGvgVpNVk4mAIbsa6baOJWGFRTiW+htQZnoJCSTqGZ5rhTxuJ/RQNU6DiLFs8UBtAnvNW4Wx1lWoVuVXOjdTRr5BtsgTpsG+A2gJsvc79hufq6AxL8OxDAGSFMVFl9ljnZWRds2KEAZI5If0pJsE/Yca+HUg2tVQ2PbCvlFmzgiWHcMxwK1L2I2S22zzTti/4/pGPqjucJ6fYFtd171JWmScz93IsVVPtUHJuY8I86G8P1DWDeaKe7N+JKHl+tlu+BrPCGLJSf1Cl+Vsh4HlwmZhVySXEzmPbBKJY0+8Lw6cIgiO6JXrYdzY9N52NFc1PFXjP1bex8LVTXzRoBaM7CnQb+3HoSI6A=

script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar

deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: euwJsFVwXlb8fB30a3IIQAN/2k3CbTKbUyK/lVEcz3XoCg2AKBbXQlngShThn00ce9/ZSb4004Tyib8Equou9zOqe7UcpqDNBN2hTIT7QGXkE5ZPZ4vhZsJnNORICI3gRthbIfnYxtUIA5oD29SIZQ51Oo8j39B8Ca2RfKCALNsiL7iBFtfBwX7Zm56U53P5ogty6gCoEousMpnSIzTMBi3w7bz59YzwlPjIQhRd1V6rlXKyW4sdgxnOe7IfP5Jj8Zdd0V/jwpA8x+54k58h2DQXPSNZlZuPJR29v3YLC+jYLZimAm30k5oS+pFyYZLD2bTRlt8fJ2ILJNdpJWSK/xX0dWZQFyEpZ6VSovETTslNIwFoFXpIpuucjnTpWYyj8iDF51IWYpISWR+4KuM1lsz/9356Yte3VjRJnx7HvP3pRSp6EBnI6xwr4uMP8VtahWzl+O0fULWq6V8WDVer2PGca2XIRHmGghpBaw7jpJN/QG6K9KqGW0wcCErYZvSc2f00oHyFpijd1LJJcXHqq2caOdMMC9Nwzm9OCrxy9JoOWNbIHtk6RD7Z68B926pHpE8QI7q3LgHyrDkLG6befH+hmonWgrrO9T0KjNg+B1aDBqhhm3+WmjjaKMGeBRPy39gtUyS5aCcXxwPJOwsA9x3QTFpj86999Gyw1PDjBvU=
  app:
    master: grandmother-api
